# Generated by Django 5.2.17 on 2026-09-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_oauthsession_socialaccount_delete_authsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='refresh_lease_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
